package gemini_asr

// OutMessage represents the output from the Gemini model in our system.
// Text: Contains the predicted text generated by the model.
// Final: Indicates whether the prediction is the final output (true) or intermediate (false).
type OutMessage struct {
	Text  string
	Final bool
}
